INSERT INTO tb_category (name, created_At) VALUES ('Books', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Electronics', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Computers', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Fashion', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Home Appliances', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Sports', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Toys', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Automotive', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Grocery', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Health & Personal Care', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Beauty', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Movies & Music', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Video Games', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Office Supplies', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Pet Supplies', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Baby Products', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Garden & Outdoor', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Tools & Home Improvement', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Kitchen & Dining', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Furniture', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Bedding & Bath', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Arts & Crafts', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Jewelry', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Watches', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Shoes', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Clothing', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Handbags & Accessories', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Luggage & Travel Gear', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Sunglasses', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Cell Phones & Accessories', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Software', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Industrial & Scientific', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Musical Instruments', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Gift Cards', NOW());
